// Generated by https://quicktype.io

// 🎯 Dart imports:
import 'dart:convert';

class TreatmentModel {
  String name;
  String description;
  String id;
  DateTime createdAt;
  DateTime updatedAt;

  TreatmentModel({
    required this.name,
    required this.description,
    required this.id,
    required this.createdAt,
    required this.updatedAt,
  });

  TreatmentModel copyWith(
    String name,
    String description,
    String id,
    DateTime createdAt,
    DateTime updatedAt,
  ) {
    return TreatmentModel(
      name: name,
      description: description,
      id: id,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'description': description,
      'id': id,
      'createdAt': createdAt.toString(),
      'updatedAt': updatedAt.toString(),
    };
  }

  factory TreatmentModel.fromMap(Map<String, dynamic> map) {
    return TreatmentModel(
      name: map['name'],
      description: map['description'],
      id: map['id'],
      createdAt: DateTime.parse(map['createdAt']),
      updatedAt: DateTime.parse(map['updatedAt']),
    );
  }

  String toJson() => json.encode(toMap());

  factory TreatmentModel.fromJson(String source) =>
      TreatmentModel.fromMap(json.decode(source));
}
